# Generated by Django 5.2.9 on 2026-01-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_name",
                    models.CharField(
                        help_text="Must exactly match Google Ads campaign name",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("tracking_url", models.URLField()),
                ("params", models.JSONField(blank=True, default=list)),
                (
                    "extract_all_params",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, extract ALL query params from final redirect URL",
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_suffix", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScriptAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=64, unique=True)),
                ("api_secret", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("final_url", models.TextField(blank=True, null=True)),
                ("extracted_value", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.mapping"
                    ),
                ),
            ],
        ),
    ]
